### ISSUE TITLE
[Feature Request] possible to launch Battle.net minimized?

### ISSUE THREAD

**Issue by Snaid1** [ShizCalev/Battlenet-Launcher#1]
if possible, could you modify the code to allow launching battle.net minimized? I don't know what would be involved in doing so. one method I saw online involved checking the "start Battle.net" check box in the battle.net settings and then adding `--autostart` to the shortcut. 

if it's not possible I understand, I just think it would be nice if it could launch the game quietly without battle.net popping up visibly.

**Comment by ShizCalev** [comment]
Unfortunately this isn't possible with battle.net. While I can open the program minimized (the actual command is `--autostarted)` without issue, it automatically opens up whenever you actually launch a game.

**Comment by ShizCalev** [comment]
Unfortunately I can't prevent the battle.net window from opening outright since it automatically opens when you actually launch a game - but I've made the window automatically close with https://github.com/ShizCalev/Battlenet-Launcher/commit/f8a92c7fe6770474b26b3aacc796bedda8d2eef7
